{"uuid": "d9b72b8d-38a2-4d6a-85fb-4e779bf09c40", "children": ["fb6d2e38-8688-4b95-b9ef-5eab388b1ac2"], "befores": [{"name": "logged_in_page", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Welcome back!'\nActual value: Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway \nCall log:\n  - LocatorAssertions.to_contain_text with timeout 5000ms\n  -   - waiting for locator(\"body\")\n  -     8 × locator resolved to <body class=\"cu-os-win\" data-app-version=\"2\" data-build-version=\"3.73.2\" data-build-time=\"2025-04-15T01:19:14.141Z\" data-git-sha=\"ebe802246c714888516b50964c8109089a322a02\">…</body>\n  -       - unexpected value \"Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\tests\\ui\\conftest.py\", line 27, in logged_in_page\n    login_page.login('milanakan2001@gmail.com', 'Milakan2307')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 21, in login\n    self.assert_text_present_on_page('Welcome back!')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 44, in assert_text_present_on_page\n    expect(self.page.locator(\"body\")).to_contain_text(text)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19136, in to_contain_text\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 201, in to_contain_text\n    await self._expect_impl(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Создание нового контекста браузера", "status": "passed", "start": 1744745826146, "stop": 1744745826296}, {"name": "Создание новой страницы", "status": "passed", "start": 1744745826296, "stop": 1744745826785}, {"name": "Авторизация с учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Welcome back!'\nActual value: Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway \nCall log:\n  - LocatorAssertions.to_contain_text with timeout 5000ms\n  -   - waiting for locator(\"body\")\n  -     8 × locator resolved to <body class=\"cu-os-win\" data-app-version=\"2\" data-build-version=\"3.73.2\" data-build-time=\"2025-04-15T01:19:14.141Z\" data-git-sha=\"ebe802246c714888516b50964c8109089a322a02\">…</body>\n  -       - unexpected value \"Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway\"\n\n", "trace": "  File \"C:\\clickup\\tests\\ui\\conftest.py\", line 27, in logged_in_page\n    login_page.login('milanakan2001@gmail.com', 'Milakan2307')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 21, in login\n    self.assert_text_present_on_page('Welcome back!')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 44, in assert_text_present_on_page\n    expect(self.page.locator(\"body\")).to_contain_text(text)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19136, in to_contain_text\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 201, in to_contain_text\n    await self._expect_impl(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Авторизация с логином: 'milanakan2001@gmail.com' и паролем: 'Milakan2307'", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Welcome back!'\nActual value: Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway \nCall log:\n  - LocatorAssertions.to_contain_text with timeout 5000ms\n  -   - waiting for locator(\"body\")\n  -     8 × locator resolved to <body class=\"cu-os-win\" data-app-version=\"2\" data-build-version=\"3.73.2\" data-build-time=\"2025-04-15T01:19:14.141Z\" data-git-sha=\"ebe802246c714888516b50964c8109089a322a02\">…</body>\n  -       - unexpected value \"Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 21, in login\n    self.assert_text_present_on_page('Welcome back!')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 44, in assert_text_present_on_page\n    expect(self.page.locator(\"body\")).to_contain_text(text)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19136, in to_contain_text\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 201, in to_contain_text\n    await self._expect_impl(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Переход на страницу входа", "status": "passed", "steps": [{"name": "Переход по URL страницы", "status": "passed", "start": 1744745826785, "stop": 1744745844641}], "start": 1744745826785, "stop": 1744745844641}, {"name": "Проверка текста 'Welcome back!' на странице", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Welcome back!'\nActual value: Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway \nCall log:\n  - LocatorAssertions.to_contain_text with timeout 5000ms\n  -   - waiting for locator(\"body\")\n  -     8 × locator resolved to <body class=\"cu-os-win\" data-app-version=\"2\" data-build-version=\"3.73.2\" data-build-time=\"2025-04-15T01:19:14.141Z\" data-git-sha=\"ebe802246c714888516b50964c8109089a322a02\">…</body>\n  -       - unexpected value \"Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway\"\n\n", "trace": "  File \"C:\\clickup\\pages\\login_page.py\", line 21, in login\n    self.assert_text_present_on_page('Welcome back!')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 44, in assert_text_present_on_page\n    expect(self.page.locator(\"body\")).to_contain_text(text)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19136, in to_contain_text\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 201, in to_contain_text\n    await self._expect_impl(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "steps": [{"name": "Проверка наличия текста ''Welcome back!'' на странице", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to contain text 'Welcome back!'\nActual value: Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway \nCall log:\n  - LocatorAssertions.to_contain_text with timeout 5000ms\n  -   - waiting for locator(\"body\")\n  -     8 × locator resolved to <body class=\"cu-os-win\" data-app-version=\"2\" data-build-version=\"3.73.2\" data-build-time=\"2025-04-15T01:19:14.141Z\" data-git-sha=\"ebe802246c714888516b50964c8109089a322a02\">…</body>\n  -       - unexpected value \"Message supplied by app.component.tsRetryClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anywayClickUp is best experienced using our mobile app.Our web app has features so BIG, they won't fit on a small screen.Open in free mobile appContinue on web anyway\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 44, in assert_text_present_on_page\n    expect(self.page.locator(\"body\")).to_contain_text(text)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19136, in to_contain_text\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 201, in to_contain_text\n    await self._expect_impl(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "parameters": [{"name": "text", "value": "'Welcome back!'"}], "start": 1744745844641, "stop": 1744745849673}], "start": 1744745844641, "stop": 1744745849673}], "parameters": [{"name": "username", "value": "'milanakan2001@gmail.com'"}, {"name": "password", "value": "'Milakan2307'"}], "start": 1744745826785, "stop": 1744745849673}], "start": 1744745826785, "stop": 1744745849678}], "start": 1744745826146, "stop": 1744745849678}], "start": 1744745826146, "stop": 1744745881810}